Statistics
vayvy/deep-sleep pull request #5
Opened 2023-07-15 12:48 UTC by sanemorak

- calculation of mean Acceleration Magnitude and Gyroscope Magnitude
- calculation of over-threshold AccelMag and GyroMag means
- applying Pearson's r, Speraman's Rank and Kendall's Rank Correlation tests for both overall means and over-threshold means
- Student's t-test for female/male groups

2023-07-15 17:18 UTC, vayvy commented on imu.ipynb
> +    "    fname = 'results/accel'+key+'.png'\n",
Here the "-" is missing after the term "accel".

2023-07-15 17:18 UTC, vayvy commented on imu.ipynb
> +    "    fname = '/Users/sanemcansinorak/Statistics/data/accelmag'+key+'.png'\n",
Here you forgot to change the directory back to the original form.

2023-07-15 17:25 UTC, vayvy requested changes

2023-07-15 17:25 UTC, vayvy commented on imu.ipynb
> +    "    fname = 'results/accel'+key+'.png'\n",
Here the "-" is missing after the term "accel".

2023-07-15 17:25 UTC, vayvy commented on imu.ipynb
> +    "    fname = '/Users/sanemcansinorak/Statistics/data/accelmag'+key+'.png'\n",
Here you forgot the change the path back to its original form.

2023-07-15 17:25 UTC, vayvy commented on imu.ipynb
> +    "    gyro = sns.lineplot(x = 'Timestamp', linewidth= lw)\n",
Why did you change the function from plot() to linepolt()? Does it give better results?

2023-07-15 17:25 UTC, vayvy commented on imu.ipynb
> +    "    fname = 'results/gyro'+key+'.png'\n",
Here the "-" is missing after the term "gyro".

2023-07-15 17:25 UTC, vayvy commented on imu.ipynb
> +    "    gyro_mag.set_title(title, fontdict={'size': title_size})\n",
Thank you ❤️

2023-07-15 17:25 UTC, vayvy commented on imu.ipynb
> +    "    fname = '/Users/sanemcansinorak/Statistics/data/gyro-mag'+key+'.png'\n",
Here you forgot the change the path back to its original form.

2023-07-15 17:25 UTC, vayvy commented on questionnaire.ipynb
This file seems fine. The only difference is the outputs. I think before committing changes to our branches we should try to always clear all the outputs to mitigate this overhead.

2023-07-16 10:56 UTC, sanemorak commented on imu.ipynb
> +    "    gyro = sns.lineplot(x = 'Timestamp', linewidth= lw)\n",
No reason, I think it gave an error at the beginning. Reverted it back

2023-07-16 10:57 UTC, sanemorak commented on imu.ipynb
> +    "    gyro_mag.set_title(title, fontdict={'size': title_size})\n",
❤️

2023-07-16 11:08 UTC, vayvy approved these changes
Looks good. I'll add the changes to the main branch. I will make a new pull request in a bit to fix a few minor fixes to the formatting of the script :)

2023-07-16 11:08 UTC, merged